previewsEnabled: false

# Database Services - FREE TIER
databases:
  - name: foodies-db
    databaseName: foodies_production
    user: foodies_user
    plan: free  # PostgreSQL free tier
    ipAllowList: []

# Backend Services - FREE TIER
services:
  # Backend Web Service - FREE TIER
  - type: web
    name: foodies-backend
    env: node
    # NO PLAN = FREE TIER for web services
    branch: main
    buildCommand: cd backend && npm ci
    # Note: Run database setup after first deployment using seed script
    startCommand: cd backend && npm start
    rootDir: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: foodies-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET  
        generateValue: true
      - key: JWT_EXPIRE
        value: "7d"
      - key: REFRESH_TOKEN_EXPIRE
        value: "30d"
      - key: SWAGGER_ENABLED
        value: "true"  # Enable for demo
      # Add your Cloudinary credentials in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        value: "dd9fyaeon"
      - key: CLOUDINARY_API_KEY
        value: "219778695899535"
      - key: CLOUDINARY_API_SECRET
        value: "5FRoXA6Lk9Vu4d3NxnYbMhxtSno"
      - key: CORS_ORIGIN
        value: "https://foodies-frontend.onrender.com,https://foodies-himaegwgu-andriis-projects-46659e9e.vercel.app,https://foodies-backend-6qrb.onrender.com"
