version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: foodies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/foodies_db
      JWT_SECRET: please-change-me
      REFRESH_TOKEN_SECRET: please-change-me-too
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - postgres

volumes:
  postgres_data:
